import './globals.css'

export const metadata = {
  title: 'Tell me a joke',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="p-8">{children}</body>
    </html>
  )
}
